name: solarex
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2 #( 1.0.0(1) at 26.05.2022 )

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  http: ^0.13.4
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.10
  video_player: ^2.4.7 # used to play video using network else from assets
  contacts_service: ^0.6.3 # used to add & get contacts list
#  permission_handler: ^8.3.0 # used to get permission
  permission_handler: ^10.1.0 # used to get permission
  visibility_detector: ^0.2.2

  loading_indicator: ^3.0.3
  dropdown_button2: ^1.4.0
#  image_picker: ^0.8.5+3
  adaptive_scrollbar: ^2.1.2
  carousel_indicator: ^1.0.6
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.9
#  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  bottom_navy_bar: ^6.0.0
  flutter_dialpad: ^1.0.4
  flutter_screenutil: ^5.5.4
  image_picker: ^0.8.6
  shared_preferences: ^2.0.15
  persistent_bottom_nav_bar: ^5.0.2
  dio: ^4.0.6
  flutter_holo_date_picker: ^1.1.0
  intl: ^0.17.0
  table_calendar: ^3.0.8
  flutter_sms: ^2.3.3
  flutter_advanced_seekbar: ^0.0.2
  share_plus: ^6.3.1


  #  date_time_picker: ^2.1.0

  #state-management
  get: ^4.6.5

#  easy_localization: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/video/
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Black.ttf
        - asset: assets/font/Inter-Bold.ttf
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-SemiBold.ttf